---
- hosts: all
  roles:
    - common
    - fluentd

##
# consul server cluster on all master nodes
# &
# consul agent cluster (joined with the servers)
# on all mesos slave nodes
##
- hosts: consul-server
  roles:
    - { role: 'consul', mode: 'server' }

- hosts: consul-agent
  roles:
    - { role: 'consul', mode: 'agent' }

##
# Install mesos-master and slave on respective nodes
# @NOTE: mesos slave/master must be stopped appropriately
##
- hosts: mesos-master
  roles:
    - { role: 'mesos', mode: 'master' }

- hosts: mesos-slave
  roles:
    - { role: 'mesos', mode: 'slave' }
