---
- hosts: all
  roles:
    - common

# @NOTE currently on all mesos master nodes
- hosts: consul-server
  roles:
    - { role: 'consul', mode: 'server' }

# @NOTE everywhere except the mesos master nodes
- hosts: consul-client
  roles:
    - { role: 'consul', mode: 'client' }

- hosts: mesos-master
  roles:
    - { role: 'mesos', mode: 'master' }

- hosts: mesos-slave
  roles:
    - { role: 'mesos', mode: 'slave' }

- hosts: edge
  roles:
    - edge

# @NOTE work in progress
# - hosts: flocker-control
#   roles:
#     - { role: 'flocker', mode: 'control' }
#
# - hosts: flocker-agent
#   roles:
#     - { role: 'flocker', mode: 'agent' }
