##
# notification handlers for mesos
#
---
- name: restart mesos-slave
  become: yes
  service:
    name: mesos-slave
    state: restarted

- name: restart mesos-master
  become: yes
  service:
    name: mesos-master
    state: restarted

- name: restart marathon
  become: yes
  service:
    name: marathon
    state: restarted
