language: python
python: "2.7"

sudo: required

install:
  - pip install "ansible>=2.0"

script:
  - ansible-playbook -i "localhost," playbook/site.yml --syntax-check
  - ansible-playbook -i "localhost," playbook/refresh_cache.yml --syntax-check
