---
- name: add consul-template for mesos nginx proxy service
  become: yes
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { 'src': 'consul-template/mesos-consul.hcl', 'dest': '/opt/consul/template.conf.d/mesos-consul.hcl' }
    - { 'src': 'consul-template/mesos-nginx.conf.ctmpl', 'dest': '/opt/consul/template.d/mesos-nginx.conf.ctmpl' }
  notify:
    - restart consul-template
  tags:
    - consul
    - mesos

- name: setup symlinks for mesos service
  become: yes
  file:
    src: '/etc/nginx/sites-available/{{ item }}'
    dest: '/etc/nginx/sites-enabled/{{ item }}'
    state: link
    force: yes
  with_items:
    - mesos-nginx.conf
  notify:
    - reload nginx
  tags:
    - consul
    - mesos
    - nginx

- name: reload nginx
  become: yes
  service:
    name: nginx
    state: reloaded
    enabled: yes
