---
# tasks file for roles/nginx
- name: add nginx ppa
  become: yes
  apt_repository:
    repo: ppa:nginx/stable
  tags:
    - nginx

- name: install latest nginx
  become: yes
  apt:
    name: nginx
    state: latest
    update_cache: yes
  tags:
    - nginx

- name: deactivate default nginx conf
  become: yes
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - reload nginx

- name: ensure nginx service
  become: yes
  service:
    name: nginx
    state: started
    enabled: yes
  tags:
    - nginx
    - always
