---
# handlers file for nginx
- name: reload nginx
  become: yes
  service:
    name: nginx
    state: reload
    enabled: yes

- name: restart nginx
  become: yes
  service:
    name: nginx
    state: restart
    enabled: yes
