##
# marathon-apps role
#
---
- name: create marathon apps directory
  file:
    path: '{{ marathon.app_dir }}'
    state: directory
  tags:
    - marathon-apps

- name: setup marathon core apps
  template:
    src: core.json.j2
    dest: '{{ marathon.app_dir }}/core.json'
  tags:
    - marathon-core
    - marathon-apps
