---
# tasks file for roles/java
- name: add Java 8 ppa
  become: yes
  apt_repository:
    repo: ppa:webupd8team/java
  tags:
    - java8

- name: update debconf for Java 8
  become: yes
  debconf:
    name: oracle-java8-installer
    question: shared/accepted-oracle-license-v1-1
    vtype: select
    value: true
  tags:
    - java8

- name: install Java 8
  become: yes
  apt:
    name: oracle-java8-installer
    state: latest
    update_cache: yes
  tags:
    - java8
