---
# handlers file for roles/docker
- name: restart docker
  become: yes
  service:
    name: docker
    state: restarted
    enabled: yes

- name: start docker
  become: yes
  service:
    name: docker
    state: started
    enabled: yes

- name: stop docker
  become: yes
  service:
    name: docker
    state: stopped
