##
# Setup the slave nodes
#
---
- name: uninstall zookeeper
  become: yes
  apt:
    name: zookeeper
    state: absent

- name: setup mesos zookeeper namespace
  become: yes
  template:
    src: mesos.zk.j2
    dest: /etc/mesos/zk
  notify:
    - restart mesos-slave

- name: setup mesos-slave hostname, ip
  become: yes
  template:
    src: mesos-slave.hostname.j2
    dest: '{{ item }}'
  with_items:
    - /etc/mesos-slave/hostname
    - /etc/mesos-slave/ip
  notify:
    - restart mesos-slave

- name: setup mesos-slave hostname, ip
  become: yes
  copy:
    content: docker,mesos
    dest: /etc/mesos-slave/containerizers
  notify:
    - restart mesos-slave

- name: setup mesos-slave hostname, ip
  become: yes
  copy:
    content: docker,mesos
    dest: /etc/mesos-slave/containerizers
  notify:
    - restart mesos-slave

- name: update executor timeout for docker
  become: yes
  copy:
    content: 10mins
    dest: /etc/mesos-slave/executor_registration_timeout
  notify:
    - restart mesos-slave

- name: stop mesos-master
  become: yes
  service:
    name: mesos-master
    state: stopped

- name: manual override for init.d scripts
  become: yes
  copy:
    content: manual
    dest: /etc/init/mesos-master.override
  notify:
    - restart mesos-slave
