---
# tasks file for roles/common
- name: install basic common packages
  become: yes
  apt:
    name: '{{ item }}'
    state: latest
  with_items:
    - git
    - curl
    - wget
    - unzip
    - vim
  tags:
    - common
    - packages

- name: add message of the day!
  become: yes
  copy:
    src: motd
    dest: /etc/motd
  tags:
    - common
    - motd

- name: update the hosts file
  become: yes
  template:
    src: hosts.j2
    dest: /etc/hosts
  tags:
    - common
    - hostsfile
