---
# tasks file for roles/common
- name: install basic common packages
  become: yes
  apt:
    name: '{{ item }}'
    state: latest
  with_items:
    - git
    - curl
    - wget
    - unzip
    - vim
  tags:
    - common
    - packages

- name: add message of the day!
  become: yes
  copy:
    src: motd
    dest: /etc/motd
  tags:
    - common
    - motd

- name: update the hosts file
  become: yes
  template:
    src: hosts.j2
    dest: /etc/hosts
  tags:
    - common
    - hostsfile

# fix for swap capabilities
- name: update grub boot default configuration
  become: yes
  lineinfile:
    dest: /etc/default/grub
    regexp: ^GRUB_CMDLINE_LINUX_DEFAULT=
    line: GRUB_CMDLINE_LINUX_DEFAULT="cgroup_enable=memory swapaccount=1"
    state: present
  notify: update grub
  tags:
    - common
    - grub
