---
- name: setup consul server configuration
  become: yes
  template:
    src: consul-server.json.j2
    dest: '{{ consul.conf_dir }}/00consul-server.json'
  notify:
    - restart consul-server

- name: start consul-server
  become: yes
  service:
    name: consul-server
    state: started
    enabled: yes
