---
- name: setup consul server configuration
  become: yes
  template:
    src: consul-server.json.j2
    dest: /opt/consul/conf.d/00consul-server.json
  notify:
    - restart consul-server

- name: add consul-ui service to checks
  become: yes
  template:
    src: consul-ui.json.j2
    dest: /opt/consul/conf.d/consul-ui.json
  notify:
    - restart consul-server

- name: start consul-server
  become: yes
  service:
    name: consul-server
    state: started
    enabled: yes
