---
- name: setup consul server configuration
  become: yes
  template:
    src: consul-server.conf.j2
    dest: /opt/consul/conf.d/consul-server.conf
  notify:
    - restart consul-server

- name: start consul-server
  become: yes
  service:
    name: consul-server
    state: started
    enabled: yes
