---
- name: setup consul agent configuration
  become: yes
  template:
    src: consul-agent.json.j2
    dest: '{{ consul.conf_dir }}/00consul-agent.json'
  notify:
    - restart consul-agent

- name: start consul-agent
  become: yes
  service:
    name: consul-agent
    state: started
    enabled: yes
