---
- name: install dnsmasq
  become: yes
  apt:
    name: dnsmasq
    state: latest
  tags:
    - dnsmasq

- name: enable DNS proxy for consul
  become: yes
  copy:
    content: server=/consul/127.0.0.1#8600
    dest: /etc/dnsmasq.d/10-consul
  notify:
    - restart dnsmasq
  tags:
    - dnsmasq

- name: check dnsmasq online
  become: yes
  service:
    name: dnsmasq
    state: started
    enabled: yes
  tags:
    - dnsmasq

- name: add dnsmasq proxy service check to consul
  become: yes
  template:
    src: dnsmasq-proxy.json.j2
    dest: '{{ consul.data_dir }}/{{ mode }}/dnsmasq-proxy.json'
  when: mode is defined
  notify:
    - restart consul-server
  tags:
    - dnsmasq
