---
# tasks file for roles/consul
- name: create a root directory for consul
  become: yes
  file:
    path: '{{ consul.data_dir }}'
    state: directory
  tags:
    - consul

- name: install consul 0.6.4
  become: yes
  unarchive:
    src: https://releases.hashicorp.com/consul/0.6.4/consul_0.6.4_linux_amd64.zip
    dest: /usr/local/bin
    mode: 'u+x'
    copy: no
    creates: /usr/local/bin/consul
  tags:
    - consul

- name: install consul-server/client init.d service
  become: yes
  template:
    src: consul.init.d.j2
    dest: '/etc/init.d/consul-{{ mode }}'
    mode: 'u+x'
  when: mode is defined
  tags:
    - consul

- include: consul-server.yml
  when: mode is defined and mode == 'server'
  tags:
    - consul

- include: consul-agent.yml
  when: mode is defined and mode == 'agent'
  tags:
    - consul

- include: consul-template.yml
  when: tmpl is defined and tmpl == True
  tags:
    - consul
    - consul-template
