---
# tasks file for roles/common
- name: install basic common packages
  become: yes
  apt:
    name: '{{ item }}'
    state: latest
  with_items:
    - g++
    - git
    - curl
    - wget
    - vim
    - ntp
    - python-pip
  tags:
    - common

- name: add message of the day!
  become: yes
  file:
    src: motd
    dest: /etc/motd
  tags:
    - common
    - motd

- name: add updated hosts file
  become: yes
  template:
    src: hosts.j2
    dest: /etc/hosts
  tags:
    - common
    - hosts_file
