---
# tasks file for roles/flocker
- name: add apt repo for flocker
  become: yes
  apt_repository:
    repo: 'deb https://clusterhq-archive.s3.amazonaws.com/ubuntu/14.04/$(ARCH) /'
    state: present
  tags:
    - flocker

- name: install flocker
  become: yes
  apt:
    name: '{{ item }}'
    state: latest
    force: yes
    update_cache: yes
  with_items:
    - clusterhq-flocker-node
    - clusterhq-flocker-docker-plugin
  tags:
    - flocker

- name: install flocker-cli
  become: yes
  apt:
    name: clusterhq-flocker-cli
    state: latest
    force: yes
    update_cache: yes
  when: mode is defined and mode == 'control'
  tags:
    - flocker
    - flocker-cli

- name: create flocker dir
  become: yes
  file:
    path: /etc/flocker
    state: directory
    recurse: yes
    mode: 0700
  tags:
    - flocker

- name: copy cluster certificate
  become: yes
  copy:
    src: '{{ flocker.cluster.cert }}'
    dest: /etc/flocker/cluster.crt
    mode: 0600
  when: mode is defined and mode == 'control'
  tags:
    - flocker
    - flocker-keys

- name: copy cluster certificate key
  become: yes
  copy:
    src: '{{ flocker.cluster.key }}'
    dest: /etc/flocker/cluster.key
    mode: 0600
  when: mode is defined and mode == 'control'
  tags:
    - flocker
    - flocker-keys
