---
# tasks file for roles/docker
- name: add self signed key for docker
  become: yes
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present
  tags:
    - docker

- name: add apt repos for docker
  become: yes
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
    state: present
  tags:
    - docker

- name: install docker
  become: yes
  apt:
    name: docker-engine
    state: latest
    update_cache: yes
  tags:
    - docker

- name: add docker group for non-sudo access
  become: yes
  group:
    name: docker
    state: present
  tags:
    - docker

- name: add current user to the docker group
  become: yes
  user:
    name: '{{ ansible_ssh_user }}'
    groups: docker
    append: yes
  notify:
    - restart docker
  tags:
    - docker

- name: add default DNS options for containers
  become: yes
  template:
    src: defaults.j2
    dest: /etc/default/docker
  notify:
    - restart docker
  tags:
    - docker

- name: ensure docker service
  become: yes
  service:
    name: docker
    state: started
  tags:
    - docker
