---
# tasks file for roles/fluentd
- name: add GPG key for fluentd
  become: yes
  apt_key:
    id: 1093DB45A12E206F
    url: http://packages.treasuredata.com/GPG-KEY-td-agent
    state: present
  tags:
    - fluentd

- name: add td-agent repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] http://packages.treasuredata.com/2/ubuntu/trusty/ trusty contrib
    state: present
  tags:
    - fluentd

- name: install latest td-agent
  become: yes
  apt:
    name: td-agent
    state: latest
    update_cache: yes
  tags:
    - fluentd

- name: create a conf directory, always included (overrides default)
  become: yes
  file:
    path: /etc/td-agent/conf.d
    state: directory
    recurse: yes
  tags:
    - fluentd

- name: create a fluentd log directory
  become: yes
  file:
    path: /var/log/fluentd-logs
    state: directory
    recurse: yes
    mode: 0755
    group: td-agent
    owner: td-agent
  tags:
    - fluentd

- name: add basic configuration file
  become: yes
  copy:
    src: td-agent.conf
    dest: /etc/td-agent
  notify:
    - restart td-agent
  tags:
    - fluentd
