##
# All zookeeper related operations
#
---
- name: start zookeeper
  become: yes
  service:
    name: zookeeper
    state: started

- name: stop zookeeper
  become: yes
  service:
    name: zookeeper
    state: stopped

- name: restart zookeeper
  become: yes
  service:
    name: zookeeper
    state: restarted

- name: reload zookeeper
  become: yes
  service:
    name: zookeeper
    state: reloaded
