---
# tasks file for roles/java
- name: add Java 8 ppa
  become: yes
  apt_repository:
    repo: ppa:openjdk-r/ppa
  tags:
    - openjdk8

- name: install Java 8
  become: yes
  apt:
    name: openjdk-8-jdk
    state: latest
    update_cache: yes
  environment:
    DEBIAN_FRONTEND: noninteractive
  tags:
    - openjdk8
