---
# vars file for roles/consul
consul:
  dc: '{{ consul_datacenter }}'
  data_dir: /opt/consul
  loglevel: INFO
  client_addr: 0.0.0.0
  # all consul agent config jsons go here
  conf_dir: /opt/consul/conf.d
  # all Consul HCLs go here
  template_conf_dir: /opt/consul/template.conf.d
  # all Consul ctmpls go here
  template_dir: /opt/consul/template.d

network:
  interface: '{{ network_interface }}'
